version: '3'
services:

# api
  swarm_test_haskell_api:
    # image: node:16.14.0
    image: swarm_haskell_api
    build:
      context: ./apps/otherlangs/haskell/test
      dockerfile: ../../../../dockers/haskell/Dockerfile_swarm_warp
    # build:
    #   context: ./apps/otherlangs/node/natural
    #   dockerfile: ../../../../dockers/node/Dockerfile
    # env_file:
    #   - .env
    #   - ./apps/.env
    #command: /bin/bash -c "npm i && node index3.js"
    #command: sh -c "cd /app && npm i && node index3.js"
    restart: unless-stopped
    ports:
      - "3200:3000"
#    depends_on:
#      - mysql
#      - postgres
    working_dir: /app
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "20m"
    #     max-file: "1"
    volumes:
      - ./apps/otherlangs/haskell/test:/app
    # networks:
    #   - app-network
    #   # - extarnal-service_network
    deploy:
     replicas: 3
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s



# networks:
#   app-network:
#     driver: bridge
    #external: true
  # extarnal-service_network:
  #   external:
  #     name: tags_app-network
# volumes:
#   dbdata:
#     driver: local
