version: '3'
services:

# api
  swarm_test_fomo_api:
    # image: node:16.14.0
    image: swarm_fomo_api
    build:
      context: ./apps/otherlangs/php/example
      dockerfile: ../../../../dockers/php/Dockerfile_swarm_fomo
    # build:
    #   context: ./apps/otherlangs/node/natural
    #   dockerfile: ../../../../dockers/node/Dockerfile
    # env_file:
    #   - .env
    #   - ./apps/.env
    #command: crystal main.cr
    #command: sh -c "cd /app && ls && /app/main"
    command: sh -c "php engineer server:start"
    restart: unless-stopped
    ports:
      - "3200:9000"
#    depends_on:
#      - mysql
#      - postgres
    working_dir: /app
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "20m"
    #     max-file: "1"
    #volumes:
    # - ./apps/otherlangs/php/example:/app
    # networks:
    #   - app-network
    #   # - extarnal-service_network
    # deploy:
    #  replicas: 3
    #  restart_policy:
    #    max_attempts: 3
    #    condition: on-failure       
    #  update_config:
    #    parallelism: 3
    #    delay: 10s



# networks:
#   app-network:
#     driver: bridge
    #external: true
  # extarnal-service_network:
  #   external:
  #     name: tags_app-network
# volumes:
#   dbdata:
#     driver: local
