version: '3.1'

services:



  logger_clickhouse:
    container_name: logger_clickhouse
    image: yandex/clickhouse-server
    env_file:
      - ../../.env
    #environment:
      # Default user and database will be created using `init-defaults.sh` script
      #CLICKHOUSE_DB: example
      #CLICKHOUSE_USER: clickhouse-user
      #CLICKHOUSE_PASSWORD: secret
    ports:
      - "8200:8123"
      # - "9000:9000"
      # - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - logger_clickhouse:/var/lib/clickhouse
      - /opt/clickhouse/log:/var/log/clickhouse-server
      - /opt/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - /opt/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    networks:
      - app-network
  # client:
  #   image: yandex/clickhouse-client
  #   command: ['--host', 'server']

#sudo docker run -it --rm --link clickhouse_1:clickhouse-server \
#             yandex/clickhouse-client --network=host --host 0.0.0.0



networks:
  app-network:
    driver: bridge
#  sender-network:
#    external:
#      name: sender_app-network

volumes:
  logger_clickhouse:
    driver: local
