FROM php:8.1.0-fpm


RUN pecl install swoole
RUN docker-php-ext-enable swoole

# RUN apt-get update && apt-get install -y libmcrypt-dev \
#     mysql-client libmagickwand-dev --no-install-recommends \
#     && pecl install imagick \
#     && docker-php-ext-enable imagick \
# && docker-php-ext-install mcrypt pdo_mysql

RUN apt-get update
RUN apt-get install -y libmcrypt-dev \
    libmagickwand-dev --no-install-recommends
# RUN pecl install imagick 
# RUN docker-php-ext-enable imagick 
# RUN docker-php-ext-install mcrypt pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install \
    pcntl



RUN apt-get install -y zip unzip libzip-dev
RUN docker-php-ext-install zip

WORKDIR /app

COPY . .

RUN composer install
RUN composer update

EXPOSE 9000
EXPOSE 9501

CMD [ "php", "bin/simps.php", "http:start"]