http:
  # app:
  #   weighted:
  #     healthCheck: {}
  #     mirroring:
  #     services:
  #     - name: appv1
  #       weight: 3
  #     - name: appv2
  #       weight: 1
  services:
    maintenance-page:
      loadBalancer:
        servers:
        - url: "http://localhost:3000/"

    with_mirroring:
      mirroring:
        service: "v1"
        mirrors:
          - name: "v2"
            percent: 50
    # with_mirroring:
    #   mirroring:
    #     service: "httpbin"
    #     mirrors:
    #       - name: "wallarm"
    #         percent: 100

    app:
      failover:
        healthCheck: {}
        service: "v1"
        fallback: "v2"
        

    v1:
      loadBalancer:
        healthCheck:
          path: /test
          interval: 20s
          timeout: 5s
        servers:
        - url: "http://localhost:3200/"
        - url: "http://localhost:3000/"

    v2:
      loadBalancer:
        healthCheck:
          path: /test
          interval: 20s
          timeout: 4s
        servers:
        - url: "http://localhost:3000/"
        - url: "http://localhost:3200/"
  routers:
    host:
      entryPoints: 
      - http
      service: with_mirroring
      rule: Host(`host.localhost`) 
      # tls:
      #   certResolver: letsEncrypt