
FROM node:16.14.0-alpine3.15
#FROM node:16.14.0
#FROM node:19.0.1-bullseye-slim
# FROM node:16.18-alpine3.15 # FROM keymetrics/pm2:latest-slim	

RUN npm install pm2@latest -g

RUN pwd && ls


WORKDIR /app
COPY . .
#RUN rm package-lock.json

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production


#RUN npm install --production

# typescript build
#RUN tsc

#--no-binary=:all: --no-deps --ignore-installed

# RUN adduser --disabled-password --gecos '' user
# USER user

EXPOSE 3000

# hyper express
CMD ["pm2-runtime", "polka.js", "-i", "6"]
#CMD ["node",  "polka.js"]

#ENTRYPOINT ["python3", "/app/api_sanic/api.py"]
#CMD ["python3", "api_sanic/api.py"]

#ENTRYPOINT ["python"]
#CMD ["main.py"]
